### PR TITLE
#158: Refactoring/codestyle

### PR DESCRIPTION
**Pull request by Doldrums**
General catch-all task for fixes, codestyle refactoring that are not related with a specific issue.
According to the style guide Ruby that recommends best practices
https://rubystyle.guide/

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@Doldrums don't forget to run `bundle exec rake` before sending a pull request

**Comment by Doldrums** [comment]
@yegor256 fixed, sorry, there were local issues with versions after installation Montenero 12.0 Beta.

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
