### PR TITLE
[#201] add `--model` flag to mark puzzles for prioritization using 0pdd

### PR DESCRIPTION
**Pull request by mbao01**
- Add `--model` flag to mark puzzles for prioritization using [0pdd](https://github.com/yegor256/0pdd#readme)

### CODE REVIEW

**Comment by mbao01** [comment]
@yegor256 please review

**Comment by yegor256** [comment]
@mbao01 the description of this feature is not clear (at least to me). How exactly will it work? Let's make it more obvious in README

**Comment by mbao01** [comment]
@yegor256 please review

**Comment by yegor256** [comment]
@mbao01 I don't understand why we need this feature here. It belongs only to 0pdd. We can add this "marker" to XML when we process it over there. Here, in the command line, why do we need to care about ML part of 0pdd project??

**Comment by mbao01** [comment]
@yegor256 I believe this feature is to allow each user (or project) to opt-in to use the ML model. I was unaware that they have access to configure 0pdd. I see that now in the 0pdd readme and will move this feature there.

**Pull request closed without merging**
