### PR TITLE
[#211] support more puzzle test cases

### PR DESCRIPTION
**Pull request by mbao01**

### CODE REVIEW

**Comment by mbao01** [comment]
@yegor256 please review

**Comment by yegor256** [comment]
@mbao01 if it fixed the problem, renamed the files in `test_assets/puzzles` directory so that their files names are not `broken-*` anymore. If after renaming the build is green -- we will know that the problem is fixed.

**Comment by mbao01** [comment]
@yegor256 I made the update. Please review again. Thanks

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
