### PR TITLE
[#178] fix crash - ENOENT

### PR DESCRIPTION
**Pull request by mbao01**

### CODE REVIEW

**Comment by mbao01** [comment]
@yegor256 please review

**Comment by yegor256** [comment]
@mbao01 what is the motivation here? xcop helps us control the formatting of XML documents

**Comment by mbao01** [comment]
xcop fails every single time. Until it is fixed, it is a blocker @yegor256

**Comment by mbao01** [comment]
I should add a separate puzzle to this.

**Comment by mbao01** [comment]
Please hold on merge @yegor256 I found a solution for this.

**Comment by mbao01** [comment]
@yegor256 please review

**Comment by mbao01** [comment]
@yegor256 please review

**Comment by mbao01** [comment]
@yegor256 please review

**Pull request merged**
